[package]
name = "test-simple-exec-script"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
sp1-sdk = { path = "../../crates/sdk" }
tokio = { version = "1.0", features = ["full"] }

[build-dependencies]
sp1-build = { path = "../../crates/build" }

